/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rbe_4815_final_project;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.File;
import java.io.FileOutputStream;
import java.util.LinkedList;
import javax.swing.JFileChooser;
import javax.swing.UIManager;

/**
 *
 * @author motmo
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        canvas_PaintJPanel.addPropertyChangeListener("isValidPath", new PropertyChangeListener(){
                 @Override
                 public void propertyChange(PropertyChangeEvent event) {
                     String property = event.getPropertyName();
                     System.out.println("Here1");
                     if ("isValidPath".equals(property)) {
                         System.out.println((boolean)event.getNewValue());
                         valid_jCheckBox.setSelected((boolean)event.getNewValue());
                        }
                 }
                });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        canvas_PaintJPanel = new rbe_4815_final_project.PaintJPanel();
        menu_jPanel = new javax.swing.JPanel();
        new_path_jButton = new javax.swing.JButton();
        save_path_jButton = new javax.swing.JButton();
        load_path_jButton = new javax.swing.JButton();
        connect_jButton = new javax.swing.JButton();
        run_jButton = new javax.swing.JButton();
        menu_jLabel = new javax.swing.JLabel();
        status_jCheckBox = new javax.swing.JCheckBox();
        valid_jCheckBox = new javax.swing.JCheckBox();
        output_jScrollPane = new javax.swing.JScrollPane();
        output_jTextPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        canvas_PaintJPanel.setPreferredSize(new java.awt.Dimension(1000, 1000));

        javax.swing.GroupLayout canvas_PaintJPanelLayout = new javax.swing.GroupLayout(canvas_PaintJPanel);
        canvas_PaintJPanel.setLayout(canvas_PaintJPanelLayout);
        canvas_PaintJPanelLayout.setHorizontalGroup(
            canvas_PaintJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        canvas_PaintJPanelLayout.setVerticalGroup(
            canvas_PaintJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 60.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 10, 20);
        getContentPane().add(canvas_PaintJPanel, gridBagConstraints);

        menu_jPanel.setBackground(new java.awt.Color(51, 51, 51));
        menu_jPanel.setLayout(new java.awt.GridBagLayout());

        new_path_jButton.setBackground(new java.awt.Color(51, 152, 220));
        new_path_jButton.setText("New Path");
        new_path_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_path_jButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        menu_jPanel.add(new_path_jButton, gridBagConstraints);

        save_path_jButton.setBackground(new java.awt.Color(51, 152, 220));
        save_path_jButton.setText("Save Path");
        save_path_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_path_jButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        menu_jPanel.add(save_path_jButton, gridBagConstraints);

        load_path_jButton.setBackground(new java.awt.Color(51, 152, 220));
        load_path_jButton.setText("Load Path");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        menu_jPanel.add(load_path_jButton, gridBagConstraints);

        connect_jButton.setBackground(new java.awt.Color(51, 152, 220));
        connect_jButton.setText("Connect");
        connect_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connect_jButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        menu_jPanel.add(connect_jButton, gridBagConstraints);

        run_jButton.setBackground(new java.awt.Color(51, 152, 220));
        run_jButton.setText("Run");
        run_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                run_jButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        menu_jPanel.add(run_jButton, gridBagConstraints);

        menu_jLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        menu_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        menu_jLabel.setText("Menu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        menu_jPanel.add(menu_jLabel, gridBagConstraints);

        status_jCheckBox.setBackground(new java.awt.Color(51, 51, 51));
        status_jCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        status_jCheckBox.setText("Status");
        status_jCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                status_jCheckBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        menu_jPanel.add(status_jCheckBox, gridBagConstraints);

        valid_jCheckBox.setBackground(new java.awt.Color(51, 51, 51));
        valid_jCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        valid_jCheckBox.setSelected(true);
        valid_jCheckBox.setText("Valid");
        valid_jCheckBox.setToolTipText("");
        valid_jCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valid_jCheckBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        menu_jPanel.add(valid_jCheckBox, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(menu_jPanel, gridBagConstraints);

        output_jScrollPane.setPreferredSize(new java.awt.Dimension(102, 302));

        output_jTextPane.setPreferredSize(new java.awt.Dimension(100, 100));
        output_jScrollPane.setViewportView(output_jTextPane);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 10.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 20, 20);
        getContentPane().add(output_jScrollPane, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void save_path_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_path_jButtonActionPerformed
        LinkedList<Domino> pathDominoes = getCanvasPaintJPanel().getDominoes();
        JFileChooser dirChooser = new JFileChooser();
        //dirChooser
        //dirChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        Integer opt = dirChooser.showSaveDialog(this);
        if (opt == JFileChooser.APPROVE_OPTION) {
            File pathFile = dirChooser.getSelectedFile();
            try {
                FileOutputStream outStream = new FileOutputStream(pathFile, false); // true to append
            
                String lines = "";
                for(Domino d : pathDominoes) {
                    int x = d.getPosition().x;
                    int y = d.getPosition().y;
                    double angle = d.getOrientation();
                    lines.concat("[" + x + ", " + y + ", " + angle + "]\n");
                }
                System.out.println(lines);
                outStream.write(lines.getBytes());
                outStream.close();
            }
            catch (Exception e){
                
            }
        }
    }//GEN-LAST:event_save_path_jButtonActionPerformed

    private void new_path_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_path_jButtonActionPerformed
        getCanvasPaintJPanel().resetPath();
        
    }//GEN-LAST:event_new_path_jButtonActionPerformed

    private void run_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_run_jButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_run_jButtonActionPerformed

    private void connect_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connect_jButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_connect_jButtonActionPerformed

    private void valid_jCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valid_jCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valid_jCheckBoxActionPerformed

    private void status_jCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_status_jCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_status_jCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    /**
     * Function to access the drawing panel
     * @return javax.swing.JPanel The jPanel canvas used for drawing on
     */
    public PaintJPanel getCanvasPaintJPanel(){
        return this.canvas_PaintJPanel;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rbe_4815_final_project.PaintJPanel canvas_PaintJPanel;
    private javax.swing.JButton connect_jButton;
    private javax.swing.JButton load_path_jButton;
    private javax.swing.JLabel menu_jLabel;
    private javax.swing.JPanel menu_jPanel;
    private javax.swing.JButton new_path_jButton;
    private javax.swing.JScrollPane output_jScrollPane;
    private javax.swing.JTextPane output_jTextPane;
    private javax.swing.JButton run_jButton;
    private javax.swing.JButton save_path_jButton;
    private javax.swing.JCheckBox status_jCheckBox;
    private javax.swing.JCheckBox valid_jCheckBox;
    // End of variables declaration//GEN-END:variables
}
